### ISSUE TITLE
improve imports (not all are working yet)

### ISSUE THREAD

**Issue by looooo** [FreeCAD/freecad.ship#1]
improve imports and test functionality!!

**Comment by sanguinariojoe** [comment]
This should fix all the remaining import problems (I already tested that):

https://github.com/FreeCAD/freecad.ship/pull/12

**Comment by luzpaz** [comment]
Do we have automated tests for this?

**Comment by sanguinariojoe** [comment]
Nope... But I can make something in the future

**Comment by luzpaz** [comment]
Fantastic! Should we close this ticket and open a new one in that case?

**Comment by sanguinariojoe** [comment]
Absolute!
