### ISSUE TITLE
Can we update this repo with any new fixes that have been added to master?

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/freecad.ship#10]
There have been some code fixes to the master `src/Mod/Ship` since this repo was created. Can we update it?

**Comment by luzpaz** [comment]
https://github.com/FreeCAD/FreeCAD/commits/master/src/Mod/Ship

**Comment by looooo** [comment]
If people do not accept the external freecad.ship it's best to stop any additional efforts with this repo.

**Comment by sanguinariojoe** [comment]
Fixed here: https://github.com/FreeCAD/freecad.ship/pull/12
