### ISSUE TITLE
Ship Weight Definition

### ISSUE THREAD

**Issue by ThomasStephen13** [FreeCAD/freecad.ship#30]
Looks like the ship weight icon can now only add ship weight. even though the position of the weight can be changed it is still showing as the entire ship weight is moving in graphical interface. Same problem with tank definition too

**Comment by sanguinariojoe** [comment]
I really should document that well in the wiki.

In FreeCAD-Ship the entities are designed to be managed just by the module tools, i.e. when you create a ship, weight or tank, you are not entitled to move/edit them, but just use the tools provided by the module.

In other words, users should first create AND PLACE the geometries that compose the entities (the ship itself, the weights and the tanks), and later create those entities (and never edit them)

**Comment by jmvil** [comment]
Hello,
I'm new on this forum, but very interested on this WB.
Using ship WB on FC 20.2,  I can´t obtain results as in tutorial II (updated  on april 14 abr 2023 a las 22:10. ). https://wiki.freecad.org/FreeCAD-Ship_s60_tutorial_(II)

For me, Weights position are NOT shown in the [3D view](https://wiki.freecad.org/3D_view). Neither the annotations.
Also I dont know if "Double-click over each cell" means on Weight FC object data tab (property value). When I do that, whole Ship object moves on 3D view, so I can see 2 ships images in 3D view:  Ship and Weight.

All the other earlier steps in tutorial part I  works fine for me.

But not weights nor TANKS.
About Tanks, 
I can create the geometry of the example in tutorial II, but I fail when try to upgrade Common part in draft WB. It says 

"
21:24:47  GuiCommand: Upgrade
21:24:47  ----------------
21:24:47  Upgrade objects
21:24:47  Unable to upgrade these objects.
"

I did try on FC English and FC spanish versions, and same bad results.


Thanks for your atention.

..................................................
My system is

[code]
OS: Ubuntu Core 20 (XFCE/xubuntu)
Word size of FreeCAD: 64-bit
Version: 0.20.2.29177 +426 (Git) Snap 517
Build type: Release
Branch: tag: 0.20.2
Hash: 930dd9a76203a3260b1e6256c70c1c3cad8c5cb8
Python 3.8.10, Qt 5.15.5, Coin 4.0.0, Vtk 7.1.1, OCC 7.6.3
Locale: Spanish/Spain (es_ES)
Installed mods: 
  * start_WF.FCMacro
  * FCInfo_material.txt
  * MeshRemodel 1.8919.0
  * FCInfo_ToolBar.FCMacro
  * ObjectInfo.FCMacro
  * InfoPlus.FCMacro
  * CenterOfMass.FCMacro
  * workfeature-macro
  * Help 1.0.3
  * Macro_CenterOfMass.png
  * Ship 2022.4.11
  * InfoPlus.svg
  * FCInfo.FCMacro
  * Alias_Manager.FCMacro
  * workfeature
  * FCparaboloide7.py
  * Curves 0.6.8
  * Aliasmanager_icon.png
  * CurvedShapes 1.0.4
  * InfoPlus
  * Manipulator 1.5.0
  * Glass (Disabled)
  * SimpleProperties.FCMacro
[/code]

**Comment by sanguinariojoe** [comment]
Hey! Sorry for the late reply.

Weights does not work like that anymore... See [here](https://wiki.freecad.org/Ship_Weight). Now they are similar to tanks, i.e. you should create a geometry to represent them (for instance points), and then execute the tool.

I have to edit that tutorial to avoid further issues. Please, let me know

**Comment by jmvil** [comment]
Thank you very much for your attention.
Ok, I did so, and now My ship has weight and then i could get a loadcondition Spreadheet with my weight automatically included. Then I could get an equilibrium sink and trim position. And also then a right GZ curve. All fine until now.

But after that I try similar with adding a tank .  I defined it as common solid of a cube and the same Iowa' S60 used before. Then, selecting the common part, I cliked for creating a new tank and I got a part  named Tank.  But from here no more progress.
I can't get the tank capacity curve. Icon is not hightlighted  when I select tank part. 
Also creating a new loadcondition the tank is ignored.  I dont know what  I'm doing wrong.

Here Attached a captured screen
Could you give me some idea? . Thanks.

![Captura de pantalla -2023-05-27 15-04-49](https://github.com/FreeCAD/freecad.ship/assets/131612063/e7197908-c8aa-48f3-a8ea-ae9728e95a81)

**Comment by jmvil** [comment]
More on this,
I get an error when trying to create a tank.

message said:
Traceback (most recent call last):
  File "/home/juan/snap/freecad/common/Mod/Ship/./freecad/ship/shipCreateTank/TaskPanel.py", line 42, in accept
    Tools.createTank(self.solids, ship)
  File "/home/juan/snap/freecad/common/Mod/Ship/./freecad/ship/shipCreateTank/Tools.py", line 43, in createTank
    tank = Instance.Tank(obj, solids, ship)
  File "/home/juan/snap/freecad/common/Mod/Ship/./freecad/ship/TankInstance.py", line 52, in __init__
    tooltip = QT_TRANSLATE_NOOP(
<class 'TypeError'>: QT_TRANSLATE_NOOP() takes 2 positional arguments but 3 were given



![Captura de pantalla -2023-05-27 16-34-59](https://github.com/FreeCAD/freecad.ship/assets/131612063/bb89f16e-c48b-474c-8b76-ee2d3b84b688)

**Comment by sanguinariojoe** [comment]
I fixed the error, please update and give it a try again

**Comment by jmvil** [comment]
Hi

Now, with the update, it works right for me. Well done.

And so I get a loading Condition, and also a GZ curve.
thanks
