### ISSUE TITLE
Translation of Ship workbench

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/freecad.ship#31]
- [x] Add translation infrastructure 
- [ ] Hook in to crowdin 

ref: https://github.com/FreeCAD/FreeCAD-addons/issues/187

**Comment by luzpaz** [comment]
Maybe we can get this going as well...now that we're in a feature freeze and there are a translators active in crowdin?

**Comment by sanguinariojoe** [comment]
No idea if there are translators indeed. I remember i did some changes to make ship translatable. But probably I am still missing some stuff

**Comment by sanguinariojoe** [comment]
Ok, I followed the guideline, so the file [resources/translation/Ship.ts](https://wiki.freecadweb.org/Translating_an_external_workbench) is ready to be uploaded to your FreeCAD Crowdin account.

Shall I add a topic on the forum? Ping Yorik here?

**Comment by luzpaz** [comment]
I got it from here :+1:  
Thank you!

**Comment by darigovresearch** [comment]
Is there anything left to get translation hooked into crowdin?

**Comment by sanguinariojoe** [comment]
ping @luzpaz

**Comment by luzpaz** [comment]
@yorikvanhavre (this is regarding adding the ShipWB addon to crowdin)

**Comment by luzpaz** [comment]
@yorikvanhavre how are we doing this again (3rd party addons + crowdin) ?

**Comment by luzpaz** [comment]
bump @yorikvanhavre @sanguinariojoe 

//cc @kaktusus @hasecilu

**Comment by hasecilu** [comment]
Isn't already translated? I'm having problems loading the WB now on latest v. I'll try an older AppImage later and check it.

**Comment by sanguinariojoe** [comment]
> Isn't already translated? I'm having problems loading the WB now on latest v. I'll try an older AppImage later and check it.

After your changes I have fixed the resources and some other minor related things. It should be working fine now

**Comment by hasecilu** [comment]
I can confirm that is now working on latest version (self-compiled with Qt6 support).

@sanguinariojoe since you know more than me of this subject, will you be interested on finish the translation (either on CrowdIn or locally with Qt Linguist)? There are few terms that I don't know I don't want to mess it up.

**Comment by sanguinariojoe** [comment]
> I can confirm that is now working on latest version (self-compiled with Qt6 support).
> 
> @sanguinariojoe since you know more than me of this subject, will you be interested on finish the translation (either on [CrowdIn](https://crowdin.com/editor/freecad-addons/32200/en-es?view=comfortable&filter=basic&value=0) or locally with Qt Linguist)? There are few terms that I don't know I don't want to mess it up.

Done!

**Comment by hasecilu** [comment]
> Done!

Looks pretty good! Now compiling the translation files with `lrelease` is enough for the UI to be translated.

I have seen the term "ship" being translated as "barco", "buque" and "nave", which should be the preferred term? maybe "nave" to match with "diseño naval"?

**Comment by sanguinariojoe** [comment]
> > Done!
> 
> Looks pretty good! Now compiling the translation files with `lrelease` is enough for the UI to be translated.
> 
> I have seen the term "ship" being translated as "barco", "buque" and "nave", which should be the preferred term? maybe "nave" to match with "diseño naval"? Also "tank": "tanque" or "depósito"?

"Buque" is clearly the most appropriate term.

"Barco" is rather common though, but a bit less technical. "Nave" is usually applied to speak about really old ships, and I think is common on South America. A rather more appropriate variant of "nave" would be "navío".

**Comment by luzpaz** [comment]
What's left here ?

**Comment by hasecilu** [comment]
Finish translation and merge them

**Comment by luzpaz** [comment]
Great job! Closing
