### ISSUE TITLE
[LGTM] Mismatch in multiple assignment

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/freecad.ship#35]
> Assigning multiple variables without ensuring that you define a value for each variable causes an exception at runtime.

https://lgtm.com/projects/g/FreeCAD/freecad.ship/?mode=tree&ruleFocus=890095

**Comment by sanguinariojoe** [comment]
Fixed in https://github.com/FreeCAD/freecad.ship/commit/45ee3821ada95bf9e8686b07d0291f7d3943cdc1
