### ISSUE TITLE
The tutorial mentions a lines drawing tool, but I don't see it?

### ISSUE THREAD

**Issue by tim-rohrer** [FreeCAD/freecad.ship#59]
As the title says...

I'm experimenting with this add on, but I don't see the Lines Drawing tool in the workbench.

Does this tool exist any more? Searched current code for expected terms, but no luck.

**Comment by sanguinariojoe** [comment]
Yeah, sorry, it us outdated. The outlines draw was dropped because freecad
offers tools to do so out of the box

**Comment by tim-rohrer** [comment]
Thanks for the quick reply. 

Can you give me a hint (or point to a tutorial/article) that describes the FreeCAD tools for doing this?

Thanks!

**Comment by shaise** [comment]
MangoJelly have some nice tutorials:
https://www.youtube.com/watch?v=-539fgU50Bw

**Comment by sanguinariojoe** [comment]
To make the slices:

https://wiki.freecad.org/Part_CrossSections

To plot:

https://wiki.freecad.org/TechDraw_Workbench

**Comment by tim-rohrer** [comment]
That should be enough to get me started. Thank you!
