### ISSUE TITLE
Mantis issue 3607 

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/freecad.ship#6]
[Ticket 3607 - "Ship" WB doesn't work using latest appimage release](https://freecadweb.org/tracker/view.php?id=3607)

@yorikvanhavre [points out](https://freecadweb.org/tracker/view.php?id=3607#c12475) that:  
> In any case this is a bug in matplotlib and not in freecad, because all that the plot module does is: "import matplotlib.pyplot". Probably a problem with the matplotlib version bundled in the appimage...

**Comment by looooo** [comment]
Internal ship enabled for manjaro package?

**Comment by luzpaz** [comment]
@looooo I don't think this is an issue anymore actually.

**Comment by looooo** [comment]
So we can close this one?
