### ISSUE TITLE
Is freecad.ship addon ready for 1.0 release?

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/freecad.ship#61]
https://blog.freecad.org/2024/08/30/1-0rc1-is-coming-next-week-lets-update-addons/

**Comment by sanguinariojoe** [comment]
I downloaded and compiled the release version, and it seems to work to me

**Comment by luzpaz** [comment]
@sanguinariojoe can you bump the version number to reflect that it's compatible with upcoming 1.0 release ?

https://github.com/FreeCAD/freecad.ship/blob/6689b383d84db517cadedd386c47ce7ae672491f/package.xml#L5-L6

**Comment by sanguinariojoe** [comment]
> @sanguinariojoe can you bump the version number to reflect that it's compatible with upcoming 1.0 release ?
> 
> https://github.com/FreeCAD/freecad.ship/blob/6689b383d84db517cadedd386c47ce7ae672491f/package.xml#L5-L6

Done!
