### ISSUE TITLE
Can't do any operations in Ship Workbench in FreeCAD 0.21.2

### ISSUE THREAD

**Issue by deichrenner** [FreeCAD/freecad.ship#64]
```
OS: macOS 14.7
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)
Installed mods: 
  * Ship 2022.4.11
```

There seems to be a reference problem in 

https://github.com/FreeCAD/freecad.ship/blob/6689b383d84db517cadedd386c47ce7ae672491f/freecad/ship/Instance.py#L30

where `QT_TRANSLATE_NOOP` is imported from `init_gui.py` which has been deleted in PR63 hasecilu:refactor/rename_commands. 

I could open up a PR to fix this, this is OK with you all (its a one line fix which I already made locally)?

**Comment by luzpaz** [comment]
cc @hasecilu :point_up_2:
