### ISSUE TITLE
name 'FreeCAD' is not defined when interacting with tool icons

### ISSUE THREAD

**Issue by Binboukami** [FreeCAD/freecad.ship#67]
FreeCAD version: FreeCAD-Daily (FreeCAD 1.1.0 Revision: 39153)
FreeCAD.Ship version: 2024.10.23
OS: Linux Mint version 21.3

After a fresh install following [this guide](https://wiki.freecad.org/Installing_on_Linux) using the PPAs, i also installed the ship addon using the addon manager.

As an initial test followed the addon page and first imported one of the sample models (s60 katamaran) and tried using the tools avaiable from the toolbar.
I then met with this error
![image](https://github.com/user-attachments/assets/0685dc0a-4472-4cb0-8947-4a4a3c67e748)

```
file "(...)/freecad/ship/shipHydrostactis/TaskPanel.py, line 37, in <module>
  QT_TRANSLATE_NOOP = FreeCAD.Qt.QT_TRANSLATE_NOOP

name 'FreeCAD' is not defined
```

At first i thought it was some linux related issue and tried checking for missing dependencies and different python versions but with no success.
Later i realized this behaviour also happened when interacting with other tools, no only just the hydrostatic analysis one.

After i checked the current source code it made sense that the behaviour would repeat itself as the line containing `QT_TRANSLATE_NOOP = FreeCAD.Qt.QT_TRANSLATE_NOOP` appears frequently across modules.

**Probable error cause and feedback**
I dont know the ins and outs of python, like if theres is an specific reason why things get aliased or if its just a project specific style in this case, but i found the issue probably arouse from:
- copy-pasting the QT_TRANSLATE_NOOP snippet between different modules and not checking if the name symbol was available in the scope
- a more lenient development environment where the FreeCAD name was globally available to the interpreter and so, it didnt error out during development

**Hotfix and proposed solution**
I attempted to fix the problem, i.e: be able to click the button and popup the task on FreeCAD and this seemed to work. Added `import FreeCAD` on line 27 without aliasing it.
![image](https://github.com/user-attachments/assets/5b43feb3-11e7-408e-9bfa-fdfd7315c579)

By adding a non aliased import, it was able to reach for the symbols. After adding the import, i was able to click on the hydrostatic analysis button and the task popped up on the side panels.
I havent tried it yet since im short on time at the time of writing this, but this same fix can probably be applied to the other modules that present the same behaviour. I'd recommend however checking if the imports can be simplified to prevent simple bugs like this.

P.S: I didnt make a pull request since i couldnt find contribution guidelines for this project

**Comment by luzpaz** [comment]
@hasecilu this looks translations related. Can you weigh-in ?

**Comment by Binboukami** [comment]
Its fixed, thanks
