### ISSUE TITLE
This Addon is seeking a Maintainer

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/freecad.ship#9]
Ship WB dev left the project and hasn't updated. Some folks in the FC community have patched it to work. But it could use a maintainer. Please let us know if you're interested in doing so.

**Comment by luzpaz** [comment]
@looooo is this OK and if so do you mind pinning this issue ?

**Comment by looooo** [comment]
thx.

**Comment by luzpaz** [comment]
@sanguinariojoe is the new maintainer, right?
